"""
Ingestion orchestration.

For each source table this module:
  1. loads the raw file (CSV, JSON, or REST API)
  2. cleans it (whitespace, casing, duplicates)
  3. validates schema + business rules
  4. upserts valid rows into the `raw` schema (idempotent)
  5. sends invalid rows to audit.rejected_records instead of dropping them

This is the "business logic" the Airflow DAG calls into - the DAG itself
just calls `ingest_all()` and does not know about pandas or SQL.
"""

from dataclasses import dataclass
from pathlib import Path

import pandas as pd
from sqlalchemy import Engine

from dataflowx.config.settings import settings
from dataflowx.database.loaders import upsert_dataframe
from dataflowx.database.queries import record_rejected_rows
from dataflowx.ingestion import api_client
from dataflowx.ingestion.csv_loader import load_csv
from dataflowx.ingestion.json_loader import load_json
from dataflowx.transformation.cleaners import drop_exact_duplicates, normalize_emails, trim_whitespace
from dataflowx.transformation.transformers import coerce_dates, coerce_numeric
from dataflowx.utils.logger import get_logger
from dataflowx.validation.schema_validator import (
    CUSTOMERS_SCHEMA,
    ORDERS_SCHEMA,
    ORDER_ITEMS_SCHEMA,
    PAYMENTS_SCHEMA,
    PRODUCTS_SCHEMA,
    validate_schema,
)
from dataflowx.validation.validation_rules import (
    VALID_PAYMENT_STATUSES,
    check_accepted_values,
    check_no_duplicate_ids,
    check_non_negative,
    check_positive_quantity,
    check_discount_not_exceed_line_value,
)

logger = get_logger(__name__)


@dataclass
class IngestionResult:
    table_name: str
    rows_loaded: int
    rows_rejected: int


def ingest_customers(engine: Engine, file_path: Path | None = None) -> IngestionResult:
    file_path = file_path or settings.raw_data_dir / "customers.csv"
    df = load_csv(file_path, required_columns=CUSTOMERS_SCHEMA.required_columns)

    df = trim_whitespace(df, ["first_name", "last_name", "city", "state", "country"])
    df = normalize_emails(df)
    df = coerce_dates(df, ["signup_date"])
    df = drop_exact_duplicates(df, subset=["customer_id"])

    result = validate_schema(df, CUSTOMERS_SCHEMA)
    valid, rejected = result.valid_rows, result.invalid_rows

    if not rejected.empty:
        record_rejected_rows(
            rejected, source=f"csv:{file_path.name}", table_name="customers",
            reason="; ".join(result.errors) or "failed validation", engine=engine,
        )

    loaded = upsert_dataframe(valid, "customers", ["customer_id"], engine)
    return IngestionResult("customers", loaded, len(rejected))


def ingest_stores(engine: Engine, file_path: Path | None = None) -> IngestionResult:
    file_path = file_path or settings.raw_data_dir / "stores.csv"
    df = load_csv(file_path, required_columns=["store_id", "store_name"])
    df = trim_whitespace(df, ["store_name", "city", "state", "country"])
    df = drop_exact_duplicates(df, subset=["store_id"])

    missing = df["store_id"].isnull() | df["store_name"].isnull()
    valid, rejected = df[~missing], df[missing]

    if not rejected.empty:
        record_rejected_rows(
            rejected, source=f"csv:{file_path.name}", table_name="stores",
            reason="missing store_id or store_name", engine=engine,
        )

    loaded = upsert_dataframe(valid, "stores", ["store_id"], engine)
    return IngestionResult("stores", loaded, len(rejected))


def ingest_products(engine: Engine, file_path: Path | None = None) -> IngestionResult:
    """
    Ingest the product catalog from the REST API, falling back to a local
    CSV snapshot if the API is unreachable (offline development, CI, or a
    flaky network). This fallback is a deliberate design choice, not a
    workaround: the pipeline should still run without external network
    access, using the synthetic data generated by scripts/generate_data.py.
    """
    file_path = file_path or settings.raw_data_dir / "products.csv"
    try:
        api_df = api_client.fetch_products()
        api_df = api_df.rename(columns={"id": "product_id", "title": "product_name"})
        api_df["store_id"] = None

        # The demo API exposes only a small catalog (currently 20 products),
        # while the synthetic order generator intentionally creates a larger
        # catalog. Keep the local snapshot as the complete demo catalog and
        # overlay API values for matching product IDs. This gives the project
        # a real API ingestion path without creating orphaned order_items.
        local_df = load_csv(file_path, required_columns=PRODUCTS_SCHEMA.required_columns)
        local_df = local_df[PRODUCTS_SCHEMA.required_columns]
        api_df = api_df[PRODUCTS_SCHEMA.required_columns]
        df = pd.concat([local_df, api_df], ignore_index=True)
        df = df.drop_duplicates(subset=["product_id"], keep="last")
        source_label = "api:products+csv:snapshot"
    except Exception as exc:
        logger.warning("Products API unavailable (%s); using local CSV snapshot", exc)
        df = load_csv(file_path, required_columns=PRODUCTS_SCHEMA.required_columns)
        source_label = f"csv:{file_path.name}"

    df = trim_whitespace(df, ["product_name", "category"])
    df = coerce_numeric(df, ["price"])
    df = drop_exact_duplicates(df, subset=["product_id"])

    result = validate_schema(df, PRODUCTS_SCHEMA)
    valid, rejected = result.valid_rows, result.invalid_rows
    valid, negative_price, _ = check_non_negative(valid, "price")
    rejected = pd.concat([rejected, negative_price], ignore_index=True)

    if not rejected.empty:
        record_rejected_rows(
            rejected, source=source_label, table_name="products",
            reason="failed validation", engine=engine,
        )

    loaded = upsert_dataframe(valid, "products", ["product_id"], engine)
    return IngestionResult("products", loaded, len(rejected))


def ingest_orders(engine: Engine, file_path: Path | None = None) -> IngestionResult:
    file_path = file_path or settings.raw_data_dir / "orders.csv"
    df = load_csv(file_path, required_columns=ORDERS_SCHEMA.required_columns)

    df = trim_whitespace(df, ["order_status"])
    df = coerce_dates(df, ["order_date"])
    df = drop_exact_duplicates(df, subset=["order_id"])

    result = validate_schema(df, ORDERS_SCHEMA)
    valid, rejected = result.valid_rows, result.invalid_rows

    if not rejected.empty:
        record_rejected_rows(
            rejected, source=f"csv:{file_path.name}", table_name="orders",
            reason="; ".join(result.errors) or "failed validation", engine=engine,
        )

    loaded = upsert_dataframe(valid, "orders", ["order_id"], engine)
    return IngestionResult("orders", loaded, len(rejected))


def ingest_order_items(engine: Engine, file_path: Path | None = None) -> IngestionResult:
    file_path = file_path or settings.raw_data_dir / "order_items.csv"
    df = load_csv(file_path, required_columns=ORDER_ITEMS_SCHEMA.required_columns)

    df = coerce_numeric(df, ["quantity", "unit_price", "discount"])
    df = drop_exact_duplicates(df, subset=["order_item_id"])

    result = validate_schema(df, ORDER_ITEMS_SCHEMA)
    valid, rejected_schema = result.valid_rows, result.invalid_rows

    if "discount" not in valid.columns:
        valid = valid.copy()
        valid["discount"] = 0

    valid, bad_quantity, _ = check_positive_quantity(valid, "quantity")
    valid, bad_price, _ = check_non_negative(valid, "unit_price")
    valid, bad_discount, _ = check_non_negative(valid, "discount")
    valid, bad_discount_value, _ = check_discount_not_exceed_line_value(valid)

    rejected = pd.concat(
        [rejected_schema, bad_quantity, bad_price, bad_discount, bad_discount_value],
        ignore_index=True,
    )
    if not rejected.empty:
        record_rejected_rows(
            rejected, source=f"csv:{file_path.name}", table_name="order_items",
            reason="failed validation", engine=engine,
        )

    loaded = upsert_dataframe(valid, "order_items", ["order_item_id"], engine)
    return IngestionResult("order_items", loaded, len(rejected))


def ingest_payments(engine: Engine, file_path: Path | None = None) -> IngestionResult:
    file_path = file_path or settings.raw_data_dir / "payments.json"
    df = load_json(file_path, required_columns=PAYMENTS_SCHEMA.required_columns)

    df = trim_whitespace(df, ["payment_method", "payment_status"])
    df = coerce_numeric(df, ["amount"])
    df = coerce_dates(df, ["payment_date"])
    df = drop_exact_duplicates(df, subset=["payment_id"])

    result = validate_schema(df, PAYMENTS_SCHEMA)
    valid, rejected_schema = result.valid_rows, result.invalid_rows

    valid, bad_amount, _ = check_non_negative(valid, "amount")
    valid, bad_status, _ = check_accepted_values(valid, "payment_status", VALID_PAYMENT_STATUSES)

    rejected = pd.concat([rejected_schema, bad_amount, bad_status], ignore_index=True)
    if not rejected.empty:
        record_rejected_rows(
            rejected, source=f"json:{file_path.name}", table_name="payments",
            reason="failed validation", engine=engine,
        )

    loaded = upsert_dataframe(valid, "payments", ["payment_id"], engine)
    return IngestionResult("payments", loaded, len(rejected))


def ingest_all(engine: Engine) -> list[IngestionResult]:
    """Run ingestion for every source table, in dependency order."""
    results = [
        ingest_customers(engine),
        ingest_stores(engine),
        ingest_products(engine),
        ingest_orders(engine),
        ingest_order_items(engine),
        ingest_payments(engine),
    ]
    for r in results:
        logger.info(
            "Ingested %s: %d loaded, %d rejected", r.table_name, r.rows_loaded, r.rows_rejected
        )
    return results
